### ISSUE TITLE
应用至其他任务

### ISSUE THREAD

**Issue by Jerrica123** [TaoYang225/AD-DROP#1]
你好 代码有点太多了学习起来很吃力，想咨询一下如果想把AD-DROP应用到其他领域任务（例如文本摘要）上应该从哪部分代码入手

**Comment by TaoYang225** [comment]
你好，需要先了解Transformers的框架，对于生成任务可以参考机器翻译的实现，核心代码是translation/self_transformers/trainer.py 里的 compute_loss函数，另外需要修改原始的模型结构以处理加入的addrop_encoder_mask
